server:
  port: 9090
  servlet:
    encoding:
      charset: "UTF-8"
      force: true
springdoc:
  version: 1
management:
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: savingFootprints
  devtools:
    add-properties: false
  profiles:
    active: local
  webflux:
    base-path: "api/v1/"
